Puizlet/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from mysite import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/',include('polls.urls')),
    path('', views.HomeView.as_view(), name = 'home')
]

Puizlet/mysite/polls/urls.py
from django.urls import path
from polls import views


app_name='polls'

urlpatterns=[
    
    path('', views.main, name='main'),
    path('makebooks/<int:latest_wordbook_id>/', views.makebooks, name = 'makebooks'),
    path('<int:wordbook_id>/', views.words, name='words'),
    path('<int:wordbook_id>/makewords/', views.makewords, name = 'makewords'),
    path('study/<int:wordbook_id>/<int:cnt>/', views.study, name='study'),
    path('result/<int:cnt>/', views.result, name='result'),
    path('check/<int:wordbook_id>/<str:eng_word>/<int:cnt>/', views.check, name='check'),
    path('remove/<int:wordbook_id>/', views.remove, name='remove'),
    path('removeword/<int:word_id>/', views.removeword, name='removeword'),
]

Puizlet/mysite/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date=models.DateTimeField('date published')
    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question=models.ForeignKey(Question,on_delete=models.CASCADE)
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

class WordBook(models.Model):
    book_name = models.CharField(max_length=200)

    def __str__(self):
        return self.book_name

class Word(models.Model):
    wordbook = models.ForeignKey(WordBook, on_delete=models.CASCADE)
    eng_word = models.CharField(max_length=200)
    kor_word = models.CharField(max_length=200)
    

    def __str__(self):
        return self.eng_word

Puizlet/mysite/mysite/views.py
from django.views.generic.base import TemplateView

class HomeView(TemplateView):
    template_name = 'home.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['app_list'] = ['polls',]
        return context

Puizlet/mysite/polls/views.py
from polls.models import Question, Choice, WordBook, Word
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from . import models
import random
from django import template

# Create your views here.

register = template.Library()

@register.simple_tag
def random_int():
    return random.randint(0, 1)

def main(request):
    wordbook_list = WordBook.objects.all()
    context = {'wordbook_list':wordbook_list}
    return render(request, 'polls/main.html', context)

def words(request, wordbook_id):
    #word_list = Word.objects.all().prefetch_related('wordbook').wordbook
    #word_list = get_object_or_404(Word, pk = wordbook_id)
    wordbook = get_object_or_404(WordBook, pk = wordbook_id)

    return render(request, 'polls/words.html',{'wordbook':wordbook})

def makebooks(request, latest_wordbook_id):
    new_book_name = request.POST['book_name']
    id = latest_wordbook_id + 1

    new_book = models.WordBook(book_name = new_book_name, id = id)
    new_book.save()
    return HttpResponseRedirect(reverse('polls:main', args=()))

def makewords(request, wordbook_id):
    wordbook = get_object_or_404(WordBook, pk = wordbook_id)
    new_eng_word = request.POST['eng_word']
    new_kor_word = request.POST['kor_word']

    new_word = models.Word(kor_word = new_kor_word, eng_word = new_eng_word, wordbook = wordbook)
    new_word.save()
    return HttpResponseRedirect(reverse('polls:words', args=(wordbook.id,)))

def study(request, wordbook_id, cnt):
    wordbook = get_object_or_404(WordBook, pk = wordbook_id)
    return render(request, 'polls/study.html', {'wordbook':wordbook, 'cnt':cnt})

def check(request, wordbook_id, eng_word, cnt):
    wordbook = get_object_or_404(WordBook, pk = wordbook_id)
    kor_word = request.POST['kor_word']

    for word in Word.objects.all:
        if word.wordbook.id == wordbook_id:
            if word.kor_word == kor_word and word.eng_word == eng_word:
                cnt = cnt + 1
                #맞음

    print(cnt)
    return HttpResponseRedirect(reverse('polls:study', args=(wordbook.id, cnt,) ))

def result(request, cnt):
    return render(request, 'polls/result.html', {'cnt':cnt})

def remove(request, wordbook_id):
    wordbook = get_object_or_404(WordBook, pk = wordbook_id)
    wordbook.delete()   

    return HttpResponseRedirect(reverse('polls:main', args=() ))

def removeword(request, word_id):
    word = get_object_or_404(Word, pk=word_id)
    wordbook_id = word.wordbook.id
    word.delete()

    return HttpResponseRedirect(reverse('polls:words', args=(wordbook_id, ) ))

            

Puizlet/mysite/polls/templates/polls/main.html
{% extends "base_polls.html" %}
{% block content %}
{% if wordbook_list %}
{% for w in wordbook_list %}
    {% if forloop.last %}
        <form action="{% url 'polls:makebooks' w.id %}" method="POST">
            {% csrf_token %}
            단어장 이름 : <input id="book_named" type="text" name="book_name" maxlength="30" required>
            <input type="submit" value="추가">
        </form>
    {% endif %}
{% endfor %}
{% else %}
    <form action="{% url 'polls:makebooks' 1 %}" method="POST">
            {% csrf_token %}
            단어장 이름 : <input id="book_named" type="text" name="book_name" maxlength="30" required>
            <input type="submit" value="추가">
        </form>
{% endif %}

<hr>

{% if wordbook_list %}
    <ul>
        {% for wordbook in wordbook_list %}
            <li>{{ wordbook.book_name }}
            <input type="button" value="편집" onClick="location.href='/polls/{{wordbook.id}}'">
            <input type="button" value="학습" onClick="location.href='/polls/study/{{wordbook.id}}/0'">
            <input type="button" value="삭제" onClick="location.href='/polls/remove/{{wordbook.id}}'">
            </li>
        {% endfor %}
    </ul>
{% else %}
<p>No WordBooks are available</p>
{% endif %}

{% endblock %}

Puizlet/mysite/polls/templates/polls/result.html
{% extends "base_polls.html" %}

{% block content %}
<h1>맞은 개수는 {{cnt}} 개 입니다 !!!!</h1>
<br>

<input type="button" value="메인으로" onClick="location.href='/polls/'">

{% endblock %}

Puizlet/mysite/polls/templates/polls/study.html
{% extends "base_polls.html" %}


{% block content %}
<h1>{{ wordbook.book_name }} 학습</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


{% for word in wordbook.word_set.all %}
    <form action="{% url 'polls:check' wordbook.id word.eng_word cnt%}" method="post">
        {% csrf_token %}
        {{word.eng_word}} : <input type="text" id="kor_word" name="kor_word">
    </form>
    <input type="submit" value="채점">
    <br>
{% endfor %}
<br>
<input type="button" value="결과보기" onClick="location.href='/polls/result/{{cnt}}'">

{% endblock %}

Puizlet/mysite/polls/templates/polls/words.html
{% extends "base_polls.html" %}

{% block content %}
<h1>{{ wordbook.book_name }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:words' wordbook.id %}" method="post">
{% csrf_token %}
{% for word in wordbook.word_set.all %}
    {{word.eng_word}}  {{word.kor_word}}
    <input type="button" value="삭제"  onClick="location.href='/polls/removeword/{{word.id}}'"/>
    <br>
    
{% endfor %}
</form>

<form action="{% url 'polls:makewords' wordbook.id %}" method="POST">
{% csrf_token %}
단어 : <input id="eng_word" type="text" name="eng_word" maxlength="30" required>
한글 뜻 : <input id="kor_word" type="text" name="kor_word" required><br>
<input type="submit" value="추가">
</form>
{% endblock %}

Puizlet/mysite/templates/base.html
<!DOCTYPE html>
<html lang = "en">
<head>

    <link rel = "stylesheet">
    <title>Puizlet</title>
</head>
<body>
    <div id = "sidebar">
    {% block sidebar %}
    <ul>
        <li><a href = "/">Puizlet Home</a></li>
        <li><a href = "/admin/">Admin</a></li>
    </ul>
    {% endblock  %}
    </div>
<h1>Puizlet : 암기가 즐거워 지는 시간</h1>

    <div id = "content">
        {% block content%}
        {% endblock %}
    </div>

</body>
</html>

Puizlet/mysite/templates/base_polls.html
{% extends "base.html" %}

{% block title %} Puizlet Application Site {% endblock %}

{% block sidebar %}

{{block.super}}
<ul>
    <li><a href = "/polls/">Puizlet Home</a></li>
</ul>

{% endblock %}

Puizlet/mysite/templates/home.html
{% extends "base.html" %}

{% block content %}
<hr>
<ul>
    {% for appname in app_list %}
    {% with appname|add:":"|add:"main" as urlvar %}
    <li><a href = "{% url urlvar %}">{{appname}}</a></li>
    {% endwith %}   
    {% endfor %}

{% endblock  %}